[workspace]
resolver = "2"
members = [
    "contracts/oracle-escrow",
    "contracts/fee-vesting",
]

[workspace.dependencies]
soroban-sdk = "21.7.6"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
strip = "symbols"
debug-assertions = false
codegen-units = 1
lto = true
panic = "abort"
