// Generated by tools/fork/make-fork-fixture.mjs from testnet at ledger 4856955.
pub const CONTRACT: &str = "CBYNRAADMOCTXSWRHU42OHJVXUPU6XTDD7CLSY3NTAL4P3QBJGRVEVR5";
pub const TOKEN: &str = "CDQWYVGS3XSALH3CNC7QHZM46REMB42BHFSUR72L6KJILQ4RJJLSI7JG";
pub const QUESTION_ID: u64 = 42;
pub const PAYER: &str = "GDVOZFYXE2OKERD75HHJKE6XRPQL2XHEA3AWJKIGE5NX5RH3APRFMGUN";
pub const AMOUNT: i128 = 2500000;
pub const DEADLINE: u32 = 4874195;
pub const INDEXED: bool = false;
/// Highest live_until of any entry in the snapshot: one ledger past it,
/// every contract entry in the fork is archived.
pub const MAX_LIVE_UNTIL: u32 = 5375315;
/// Entries with a TTL (contract data/code) that a refund must restore.
pub const ARCHIVABLE_ENTRIES: u32 = 5;
