// Generated by tools/fork/make-fork-fixture.mjs from testnet at ledger 4857022.
pub const CONTRACT: &str = "CD4PC6IIE732FCHLUNFMD72OYIMJRF6RHQULGXW4KR7V5HHXHEX36DWJ";
pub const TOKEN: &str = "CDQWYVGS3XSALH3CNC7QHZM46REMB42BHFSUR72L6KJILQ4RJJLSI7JG";
pub const QUESTION_ID: u64 = 1002;
pub const PAYER: &str = "GDMARUYN6BV37D7JJOAMHDP6RQHVX5QU55ZU7AXOJYN6YJUGOGZGA2BH";
pub const AMOUNT: i128 = 5000000;
pub const DEADLINE: u32 = 4874095;
pub const INDEXED: bool = true;
/// Highest live_until of any entry in the snapshot: one ledger past it,
/// every contract entry in the fork is archived.
pub const MAX_LIVE_UNTIL: u32 = 5375213;
/// Entries with a TTL (contract data/code) that a refund must restore.
pub const ARCHIVABLE_ENTRIES: u32 = 10;
